import { contextBridge, ipcRenderer } from 'electron';
contextBridge.exposeInMainWorld('alarmAPI', {
  load: () => ipcRenderer.invoke('alarms:load'),
  save: (alarms: unknown[]) => ipcRenderer.invoke('alarms:save', alarms),
  // 响铃由主进程调度,渲染层只负责显示遮罩与发声
  onRing: (cb: (alarm: unknown) => void) => { ipcRenderer.on('alarm:ring', (_e, alarm) => cb(alarm)); },
  onStopRing: (cb: () => void) => { ipcRenderer.on('alarm:stop', () => cb()); },
  onAlarmsChanged: (cb: (alarms: unknown[]) => void) => { ipcRenderer.on('alarms:changed', (_e, list) => cb(list)); },
  dismissAlarm: () => ipcRenderer.invoke('alarm:dismiss'),
  pickAudio: () => ipcRenderer.invoke('audio:pick'),
  loadHolidays: () => ipcRenderer.invoke('holidays:load'),
  openMusicSite: () => ipcRenderer.invoke('music:site'),
  openMusicApp: () => ipcRenderer.invoke('music:open'),
  onSoundsUpdated: (cb: () => void) => { ipcRenderer.on('sounds:updated', cb); },
  onDownloadStarted: (cb: (token: string, name: string) => void) => { ipcRenderer.on('download:started', (_e, token, name) => cb(token, name)); },
  onDownloadBefore: (cb: (token: string, name: string) => void) => { ipcRenderer.on('download:before', (_e, token, name) => cb(token, name)); },
  onDownloadProgress: (cb: (token: string, name: string, received: number, total: number) => void) => { ipcRenderer.on('download:progress', (_e, token, name, received, total) => cb(token, name, received, total)); },
  onDownloadDone: (cb: (token: string, final: string) => void) => { ipcRenderer.on('download:done', (_e, token, final) => cb(token, final)); },
  onDownloadFailed: (cb: (token: string) => void) => { ipcRenderer.on('download:failed', (_e, token) => cb(token)); },
  confirmDownload: (token: string, name: string) => ipcRenderer.invoke('download:confirm', token, name),
  cancelDownload: (token: string) => ipcRenderer.invoke('download:cancel', token),
  listSounds: () => ipcRenderer.invoke('sounds:list'),
  renameSound: (oldName: string, newName: string) => ipcRenderer.invoke('sounds:rename', oldName, newName),
  deleteSound: (name: string) => ipcRenderer.invoke('sounds:delete', name),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setCloseAction: (action: 'minimize' | 'exit' | null) => ipcRenderer.invoke('settings:setClose', action),
  setDismiss: (key: string, seconds: number) => ipcRenderer.invoke('settings:setDismiss', key, seconds),
  onSettingsChanged: (cb: (prefs: { dismissKey: string; dismissHoldSeconds: number }) => void) => { ipcRenderer.on('settings:changed', (_e, prefs) => cb(prefs)); },
  setAutoLaunch: (on: boolean) => ipcRenderer.invoke('settings:setAutoLaunch', on),
  openSoundsDir: () => ipcRenderer.invoke('settings:openSoundsDir'),
  openExternal: (url: string) => ipcRenderer.invoke('app:openExternal', url),
  // 像素风格界面:自绘窗口按钮 + 大窗/小窗切换
  winMinimize: () => ipcRenderer.invoke('win:minimize'),
  winClose: () => ipcRenderer.invoke('win:close'),
  setCompact: (compact: boolean) => ipcRenderer.invoke('win:setCompact', compact),
  isCompact: () => ipcRenderer.invoke('win:isCompact'),
  onCompactChanged: (cb: (compact: boolean) => void) => { ipcRenderer.on('win:compactChanged', (_e, compact) => cb(compact)); }
});
